### ISSUE TITLE
Add RISC-V Support

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-embedded#20]
e.g., https://www.espressif.com/en/products/socs/esp32-c3
https://docs.espressif.com/projects/esp-idf/en/stable/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html

**Comment by trigpolynom** [comment]
Would love to have a crack at this one

**Comment by mkannwischer** [comment]
Cool!
Just a warning: I have never used that core and I don't know anyone who has. 
So this may be either frustrating to get to work or not produce very stable benchmarks or both.

Do you happen to have the hardware to try? 
Maybe we use https://mou.sr/3vqVjIw? I could get some of those too.

**Comment by trigpolynom** [comment]
I have the following:

Microcontroller: SiFive Freedom E310 (FE310-G002)
CPU: SiFive E31 CPU
Architecture: 32-bit RV32IMAC
Speed: 256 MHz (default), 320MHz (Max)
Performance: 1.61 DMIPs/MHz
Memory: 16 KB Instruction Cache, 16 KB Data Scratchpad
Other Features: Hardware Multiply/Divide, Debug Module, Flexible Clock Generation with on-chip oscillators and PLLs

I got liboqs running on QEMU's riscv_32 so I was feeling confident about getting this working but now I'm not so confident after your comment hahah

**Comment by mkannwischer** [comment]
The ESP32-C3 is quite a bit cheaper than the SiFive board which is why I'd favor it. I was kind of hoping we can establish it as the standard benchmarking platform for 32-bit RISC-V (for crypto engineering papers). 

But if you want to give it a try with the SiFive board first, then that'd also be okay for me. I have one somewhere as well.

**Comment by mkannwischer** [comment]
Resolved by #50
