### ISSUE TITLE
Dual-licensing of pqm4-sourced code

### ISSUE THREAD

**Issue by mkannwischer** [pq-code-package/mlkem-c-embedded#5]
We'll be moving over several files over from https://github.com/mupq/pqm4 and https://github.com/mupq/mupq 
that have **unproblematic licenses**.

Most of them are authored by pqm4-maintainers (including myself) and are covered by a CC0 license waiver; these should be the easy cases. 
We'll dual-license those under Apache-2.0 + CC0. We'll keep track of them here, to make sure the dual-licenses are properly back-ported to pqm4/mupq. 

There are some files based on public domain implementations of Keccak/FIPS202, e.g., https://github.com/mupq/mupq/blob/master/common/keccakf1600.c. 
The original implementations are public domain, and the modifications are covered by the mupq/pqm4 CC0 waiver.
I'm unsure how to properly handle those. Some input would be appreciated.

**Comment by hartm** [comment]
I've asked LF legal about this one.  This is a case that I haven't seen before.  I'll get back to you all once I hear back.  Thanks!

**Comment by mkannwischer** [comment]
For the easy cases I added the dual-license in pqm4: https://github.com/mupq/pqm4/pull/335
I had discussed this with my co-maintainer @rpls and we'll have it merged shortly.
